requirejs.config({
    "urlArgs": "bust=" + (new Date()).getTime(),
    "paths":{
        "Border":"js/draw/Border",
        "Canvas":"js/draw/Canvas",
        "Color":"bower_components/CanvasEngine/src/core/Color",
        "Imagem":"js/draw/Imagem",
        "LinearGradient":"js/draw/LinearGradient",
        "RadialGradient":"js/draw/RadialGradient",
        "Shadow":"js/draw/Shadow",
        "Game":"js/main/Game",
        "Body":"js/physics/Body",
        "Contact":"js/physics/Contact",
        "DistanceJoin":"js/physics/DistanceJoint",
        "Friction":"js/physics/Friction",
        "FrictionPhysics":"js/physics/FrictionPhysics",
        "Join":"js/physics/Joint",
        "Material":"js/physics/Material",
        "MouseBody":"js/physics/MouseBody",
        "MV":"js/physics/MV",
        "QuadTree":"js/physics/QuadTree",
        "RevolutionJoint":"js/physicis/RevolutionJoint",
        "SurfaceJoint":"js/physics/SurfaceJoint",
        "World":"js/physics/World",
        "Arc":"js/shapes/Arc",
        "Circle":"js/shapes/Circle",
        "Point":"js/shapes/Point",
        "Polygon":"js/shapes/Polygon",
        "Rect":"js/shapes/Rect",
        "Regular":"js/shapes/Regular",
        "Shape":"js/shapes/Shape",
        "Trapezius":"js/shapes/Trapezius",
        "Triangle":"js/shapes/Triangle",
        "jquery-tmp":"bower_components/jquery/dist/jquery.min",
        "jquery":"js/utils/jquery",
        "main":"js/main/main",
        "MouseReader":"bower_components/CanvasEngine/src/Reader/MouseReader",
        "KeyReader":"bower_components/CanvasEngine/src/Reader/KeyReader",
        "CanvasEngine":"bower_components/CanvasEngine/src/core/CanvasEngine",
        "CanvasLayer":"bower_components/CanvasEngine/src/core/CanvasLayer",
        "AppObject":"bower_components/CanvasEngine/src/core/AppObject",
        "Math":"bower_components/MathLib/src/Math",
        "GameEditor":"js/main/build/GameEditor",
        "ToolMenu":"bower_components/ReactElements/build/ToolMenu",
        "React":"bower_components/react/react.min",
        "InputNumberMixin":"bower_components/ReactElements/build/mixins/inputNumberMixin",
        "InputNumberVertical":"bower_components/ReactElements/build/InputNumberVertical",
        "SetIntervalMixin":"bower_components/ReactElements/build/mixins/setIntervalMixin",
        "chart":"bower_components/AdminLTE/plugins/chartjs/Chart.min",
        "lodash":"bower_components/lodash/lodash.min",
        "QuadTest":"js/main/build/QuadTest"
    },
    "shim":{
        "LinearGradient":{
            deps:["Color"]
        },
        "RadialGradient":{
            deps:["Color"]
        },
        "Game":{
            deps:['World','Canvas','MV']
        },
        "main":{
            deps:[
                'jquery',
                'GameEditor'
            ]
        },
        "Body":{
            deps:['Shape','Material','MV','FrictionPhysics']
        },
        "DistanceJoint":{
            deps:["Joint"]
        },
        "MouseBody":{
            deps:['Body','Material','Shape','MV','Rect']
        },
        "QuadTree":{
            deps:['Body','FrictionPhysics']
        },
        "World":{
            deps:['QuadTree','MV','FrictionPhysics']
        },
        "Arc":{
            deps:['Border','Shape']
        },
        "Circle":{
            deps:["Arc"]
        },
        "Polygon":{
            deps:['Shape','Color','Border','MV']
        },
        "Rect":{
            deps:['Polygon']
        },
        "Regular":{
            deps:['Polygon','MV']
        },
        "Shape":{
            deps:['Color','Point']
        },
        "Trapezius":{
            deps:["Polygon"]
        },
        "Triangle":{
            deps:["Polygon"]
        },
        "KeyReader":{
            deps:["jquery"]
        },
        "MouseReader":{
            deps:["jquery"]
        },
        "jquery":{
            deps:["jquery-tmp"]
        },
        "FrictionPhysics":{
            deps:["MV",'Contact']
        },
        "Canvas":{
            deps:['MV','Body','Polygon','LinearGradient','RadialGradient','Color']
        },
        "CanvasEngine":{
            deps:['AppObject','Math','MouseReader','CanvasLayer']
        },
        "CanvasLayer":{
            deps:['jquery','AppObject']
        },
        "InputNumberVertical":{
            deps:["InputNumberMixin","React"]
        },
        "InputNumberMixin":{
            deps:["SetIntervalMixin","React"]
        },
        "GameEditor":{
            deps:['Game','React','ToolMenu','Rect','Math','Body','Material','Polygon']
        },
        "AppObject":{
            deps:["lodash"]
        },
        "QuadTest":{
            deps:['AppObject','Game']
        }
    }
});